Repository z0s3r77/BooKingBikeV2, pull requests merged in 2022-12, with the labels that each got.

#9 Feature/sebas
  docs/home.html
  index.html
Labels: enhancement

#10 Feature/miguel
  src/db/conexionApiMongo.py
Labels: enhancement

#11 fix: Se ha encapsulado la peticion en requesToMongoApi
  src/db/conexionApiMongo.py
Labels: invalid

#16 feat: Implementado el modulo generadorJson.py
  .gitignore
  JSON/bikes.json
  src/db/generadorJson.py
Labels: enhancement

#17 feat: Creamos la pagina listadotipobicis
  docs/listadotipobicis.html
Labels: enhancement

#19 feat: Creado plantilla de especificaciones tecnicas
  docs/B1.html
Labels: enhancement

#22 fix: Se han corregido todos los enlaces y etiquetas semanticas
  docs/B1.html
  docs/home.html
  docs/listadobicisporzona.html
  docs/listadomarcabicis.html
  docs/listadotipobicis.html
  docs/listadototalbicis.html
Labels: bug

#23 Feature/cambiar json a lista
  src/db/cambiarJsonALista.py
Labels: enhancement

#24 perf: Se ha mejorado conexionApiMongo.py , generadorJson.py
  src/db/__init__.py
  src/db/conexionApiMongo.py
  src/db/generadorJson.py
Labels: bug, enhancement

#26 perf: Añadida funcionalidad en generadorJson.py
  src/db/generadorJson.py
Labels: enhancement

#27 perf: Se ha cambio el nombre del archivo a convertirJsonALista.py
  src/db/convertirJsonALista.py
Labels: bug

#28 Feature/contacto
  docs/contacto.html
Labels: enhancement

#31 fix: eliminar filtro
  src/db/conexionApiMongo.py
Labels: bug

#33 Feature/typer
  json/bikes.json
  json/prueba.json
  requirements.txt
  src/crud/main.py
  src/typer/main.py
Labels: enhancement

#35 feat: Se ha añadido .env
  src/crud/MongoAtlasConexion.py
  src/crud/main.py
Labels: enhancement

#34 Feature/main
  docs/contacto.html
  json/bikes.json
  src/db/conexionApiMongo.py
  src/views/crearPaginaPorBicicleta.py
  src/views/creardiccionarios.py
  src/views/funcionesHTML.py
  src/views/main.py
Labels: bug, enhancement

#38 feat: Añadimos la generación de carpetas (funcionesHTML.py)
  src/views/funcionesHTML.py
Labels: enhancement

#42 fix: Arreglando titulo y descripción
  docs/bikes/B1.html
  docs/bikes/B10.html
  docs/bikes/B2.html
  docs/bikes/B3.html
  docs/bikes/B4.html
  docs/bikes/B5.html
  docs/bikes/B6.html
  docs/bikes/B8.html
  docs/bikes/B9.html
  docs/brand/Canyon.html
  docs/brand/Orbea.html
  docs/brand/Trek.html
  docs/brand/shimano.html
  docs/contacto.html
  docs/developments/1x11.html
  docs/developments/1x12.html
  docs/developments/1x7.html
  docs/developments/2x12.html
  docs/home.html
  docs/listadobicisporcambio.html
  docs/listadobicispordesarollo.html
  docs/listadobicisportamañorueda.html
  docs/listadobicisporzona.html
  docs/listadomarcabicis.html
  docs/listadotipobicis.html
  docs/listadototalbicis.html
  docs/location/Campos.html
  docs/location/Manacor.html
  docs/location/Palma.html
  docs/location/Santanyi.html
  docs/shifts/automatica.html
  docs/shifts/manual.html
  docs/types/CityBike.html
  docs/types/MTB.html
  docs/types/Road Bike.html
  docs/wheelsize/12.html
  docs/wheelsize/20.html
  docs/wheelsize/27.5.html
  docs/wheelsize/28.html
  docs/wheelsize/29.html
  src/views/funcionesHTML.py
  src/views/main.py
Labels: bug

#44 fix: Arregramos el filtrado por desarrollo
  docs/listadobicispordesarrollo.html
  src/views/funcionesHTML.py
Labels: bug

#46 Feature/pytest
  src/db/convertirJsonALista.py
  src/db/generadorJson.py
  src/db/mainDb.py
  src/views/funcionesHTML.py
  src/views/main.py
  test/pruebas/buenjson.txt
  test/pruebas/maljson.txt
  test/test_DB_convertirJsonALista.py
  test/test_DB_generadorJson.py
  test/test_DB_mainDB.py
Labels: enhancement

#49 Feature/pytest
  pytest.ini
  src/crud/main.py
  src/typer/__init__.py
  src/typer/main.py
  test/pruebas/buenjson.txt
  test/test_DB_convertirJsonALista.py
  test/test_DB_mainDB.py
  test/test_TYPER_insertar_documento.py
  test/test_TYPER_listar_documentos.py
Labels: enhancement

#51 Feature/pytest
  pytest.ini
  src/crud/main.py
  src/typer/main.py
  test/test_CRUD_main.py
  test/test_TYPER_actualizar_documento.py
Labels: enhancement

#54 Feature/añadir css
  docs/index.html
  json/prueba2.json
  requirements.txt
  src/views/crearPaginaPorBicicleta.py
  src/views/crearcss.py
  src/views/funcionesHTML.py
  src/views/main.py
Labels: bug, duplicate
